# Generated by Django 5.1.7 on 2025-03-15 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_mycontact_profile_role'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mycontact',
            old_name='telegram',
            new_name='address',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='email',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='phone',
        ),
        migrations.AddField(
            model_name='profile',
            name='telegram',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
    ]
