# Generated by Django 5.1.7 on 2025-03-15 17:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0003_rename_telegram_mycontact_address_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='MyContact',
            new_name='MyInfo',
        ),
    ]
