# Generated by Django 5.1.7 on 2025-03-15 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0005_profile_instagram_profile_x'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='telegram',
            field=models.URLField(blank=True, null=True),
        ),
    ]
