# Generated by Django 5.1.7 on 2025-03-15 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0006_alter_profile_telegram'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skill',
            name='level',
            field=models.CharField(choices=[('Junior', 'Junior'), ('Middle', 'Middle'), ('Senior', 'Senior'), ('Lead', 'Lead'), ('Expert', 'Expert')], max_length=50),
        ),
    ]
