"""
Django settings for core project.

Generated by 'django-admin startproject' using Django 5.1.1.

For more information on this file, see
https://docs.djangoproject.com/en/5.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.1/ref/settings/
"""

from pathlib import Path
import environ
import os
# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent
env = environ.Env()
environ.Env.read_env()
# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = env('SECRET_KEY')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['*','abbostech.uz']


# Application definition

INSTALLED_APPS = [
    'jazzmin',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'tailwind',
    'pages',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'core.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR.joinpath('templates')],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'core.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.1/ref/settings/#databases
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / "db.sqlite3",
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

JAZZMIN_SETTINGS = {
    "site_title": "Mening Admin Panelim",  # Brauzer ichida chiqadigan sarlavha
    "site_header": "Admin Panel",  # Saytning yuqori qismi
    "site_brand": "Mening Saytim",  # Chap yuqoridagi brend nomi
    "welcome_sign": "Xush kelibsiz, Admin!",  # Kirish sahifasida ko‘rinadigan matn
    "copyright": "© 2024 Abbosbek. Barcha huquqlar himoyalangan",  # Sayt pastki qismi

    # Navbar va footer sozlamalari
    "show_ui_builder": False,  # UI Builder tugmasini o‘chirish
    "user_avatar": None,  # Foydalanuvchi profil rasmi
    "topmenu_links": [
        {"name": "Bosh sahifa", "url": "admin:index", "permissions": ["auth.view_user"]},
        {"model": "auth.User"},  # Admin panelda Users modelini ko‘rsatish
    ],
    
    # Yon menyuni sozlash
    "navigation_expanded": True,  # Yon panel avtomatik ochiq turadi
    "hide_apps": [],  # Agar kerak bo‘lsa, ayrim ilovalarni yashirish mumkin
    "hide_models": [],  # Yashiriladigan modellarni qo‘shish mumkin

    # Foydalanuvchi profili sahifasini ko‘rsatish
    "custom_links": {
        "auth": [{"name": "Yangi foydalanuvchi qo‘shish", "url": "admin:auth_user_add", "icon": "fas fa-user-plus"}]
    },

    # Templateni tanlash
    "changeform_format": "horizontal_tabs",  # Formalarni ko‘rinishini o‘zgartirish
}

# Internationalization
# https://docs.djangoproject.com/en/5.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'Asia/Tashkent'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.1/howto/static-files/


STATIC_URL = 'static/'

# Frontend static fayllar uchun papka
STATICFILES_DIRS = [
    os.path.join(BASE_DIR, 'static'),  # Bu papka loyihaning ichida bo‘lishi kerak
]

# Static fayllarni yig‘ish uchun papka (deploy uchun)
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles') 

MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')
# Default primary key field type
# https://docs.djangoproject.com/en/5.1/ref/settings/#default-auto-fieldc

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
